name: polling_generated_events
version: "1.0.0"
config-version: 2

profile: polling_generated_events

model-paths:
  - models

macro-paths:
  - macros

clean-targets:
  - target
  - dbt_packages

on-run-start:
  - "{{ ensure_raw_external_table() }}"

models:
  polling_generated_events:
    +materialized: table
    +format: parquet
    +table_type: hive
