name: format-check

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  formatting:
    uses: amcaughan/shared_workflows/.github/workflows/format-check.yml@5493055aceacdec37edc5c9bb9da0ec1ed820fe0
    with:
      terraform_modules_dir: infra/terragrunt/modules
      terragrunt_working_dir: infra/terragrunt
